### ISSUE TITLE
Packaging for Linux

### ISSUE THREAD

**Issue by seasharpfoss** [gerlofvanek/basicswap-installation-GUI#24]
Hi There,

I'm working on [BasicSwap Issue #19](https://github.com/tecnovert/basicswap/issues/19#issuecomment-2098951043) which concerns building an image based basicswap package.

An electron GUI interface for setup would be a great fit, so I'm investigating building this project for linux to serve that purpose.

Please pass along any information you think I might need to achieve this, and in the meantime I'll try building for Linux and report back.

**Comment by seasharpfoss** [comment]
Okay, I've taken a swing at getting a flatpak out. Here's where I'm stuck:

Clone https://github.com/seasharpfoss/basicswap-installation-GUI/tree/flatpak

Modify electron-gui/package.json as follows
```
diff --git a/electron-gui/package.json b/electron-gui/package.json
index f5647a5..4027b7f 100644
--- a/electron-gui/package.json
+++ b/electron-gui/package.json
@@ -3,13 +3,7 @@
   "version": "1.0.0",
   "description": "",
   "main": "src/main.js",
-  "scripts": {
-    "start": "electron .",
-    "package-win": "electron-packager . basicswap-installer --overwrite --platform=win32 --arch=ia32,x64 --icon=assets/icons/icon.ico --prune=true --out=release-builds",
-    "package-mac": "electron-packager . basicswap-installer --overwrite --platform=darwin --arch=x64 --icon=assets/icons/icon.icns --prune=true --out=release-builds",
-    "package-linux": "electron-packager . basicswap-installer --overwrite --platform=linux --arch=x64 --icon=assets/icons --prune=true --out=release-builds"
-  },
-  "keywords": [],
+   "keywords": [],
   "author": "",
   "license": "ISC",
   "dependencies": {
```
Run the following
`npx electron-forge import`

The following output is produced
```
✔ Checking your system
? WARNING: We will now attempt to import: "/tmp/basicswap-installation-GUI/electron-gui".  This will involve modifying some files, are you sure you want to continue? Yes
✔ Initializing Git Repository
? Do you want us to change the "main" attribute of your package.json?  If you are currently using babel and pointing to a "build" directory say yes. Yes
? Enter the relative path to your uncompiled main file src/main.js
? Do you want us to remove the "electron-packager" dependency in package.json? Electron Forge already uses this module as a transitive dependency. Yes
? Do you want us to update the "start" script to instead call the electron-forge task "electron-forge start" Yes
? Do you want us to update the "package" script to instead call the electron-forge task "electron-forge package" Yes
? Do you want us to update the "make" script to instead call the electron-forge task "electron-forge make" Yes
✔ Writing modified package.json file
✖ Pruning deleted modules

An unhandled error has occurred inside Forge:
Exited with status 1
Error: Exited with status 1
    at closeArgsToError (/home/m00t/.npm/_npx/6913fdfd1ea7a741/node_modules/cross-spawn-promise/lib/index.js:20:16)
    at ChildProcess.<anonymous> (/home/m00t/.npm/_npx/6913fdfd1ea7a741/node_modules/cross-spawn-promise/lib/index.js:76:19)
    at Object.onceWrapper (node:events:632:26)
    at ChildProcess.emit (node:events:517:28)
    at ChildProcess._handle.onexit (node:internal/child_process:292:12)
```

Being unfamiliar with node, yarn, electron, I'm not sure yet how to move forward. I think I'll revert to creating the electron app package folder and perhaps try running that on a test system.

Please let me know if you can help. Thanks!
